# Generated by Django 4.2.20 on 2025-04-03 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the event title', max_length=255, verbose_name='title')),
                ('event_start', models.DateTimeField(help_text='Event start date and time', verbose_name='start time')),
                ('event_end', models.DateTimeField(help_text='Event end date and time', verbose_name='end time')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['event_start'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the participant is still active in the event', verbose_name='active participation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='events.event', verbose_name='event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='participant')),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
                'ordering': ['-joined_at'],
                'unique_together': {('event', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(help_text='Users participating in the event', related_name='events', through='events.EventParticipant', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_start'], name='events_even_event_s_28d600_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_end'], name='events_even_event_e_7b2140_idx'),
        ),
    ]
